#!/bin/sh

export GOPATH=~/.gocode

go get github.com/go-martini/martini
go get github.com/go-sql-driver/mysql
go get github.com/jinzhu/gorm

export GOPATH=$GOPATH:`pwd`

mkdir quotes >/dev/null

go build server.go
echo build done

./server

