<?php

namespace AppBundle\Repository;

/**
 * AtrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtrRepository extends \Doctrine\ORM\EntityRepository
{
}
