<?php

namespace AppBundle\Repository;

/**
 * ChariotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChariotRepository extends \Doctrine\ORM\EntityRepository
{
}
