<?php

namespace AppBundle\Repository;

/**
 * CsvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CsvRepository extends \Doctrine\ORM\EntityRepository
{
}
