<?php

namespace AppBundle\Repository;

/**
 * MaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaRepository extends \Doctrine\ORM\EntityRepository
{
}
