<?php

namespace AppBundle\Repository;

/**
 * RiskyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RiskyRepository extends \Doctrine\ORM\EntityRepository
{
}
