<?php

namespace AppBundle\Repository;

/**
 * SkipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkipRepository extends \Doctrine\ORM\EntityRepository
{
}
